apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-manager-chart.fullname" . }}
  labels:
    app: task-manager
spec:
  type: {{ .Values.service.type }}
  selector:
    app: task-manager
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP   